server:
  port: 8081

spring:
  application:
    name: api-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/harbormart_auth
    username: harbormart_user
    password: harbormart_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/harbormart_auth
    user: harbormart_user
    password: harbormart_password

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expirationMs: 86400000 # 24 hours
